### ISSUE TITLE
C3 cell of spreadsheet.ods of "a simple example" is not treated as currency by LibreOffice

### ISSUE THREAD

**Issue by mahiuchun** [chrisbyboston/ezodf2#1]
See the screenshot
![screen shot 2013-08-07 at 10 35 58 pm](https://f.cloud.github.com/assets/1404381/924839/1b802b90-ff6f-11e2-9c60-d740f35b1b48.png)

**Comment by chrisbyboston** [comment]
Thanks for the screenshot. I maintain this package with a generous view towards merging pull requests. So if you'd like to contribute directly, just write a fix and a test if applicable. I'll review and merge if it all looks good. Otherwise, it might be a few weeks before I get a chance to look at it. Thanks again!
